services:
  opera-panel:
    build: .
    ports:
      - "5055:5055"
    env_file:
      - .env
    environment:
      - STARDUST_API_BASE_URL=https://stardust.my-firstcare.com
      - STARDUST_AUTH_URL=https://stardust.my-firstcare.com
      - SECRET_KEY=opera-panel-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - PANEL_HOST=0.0.0.0
      - PANEL_PORT=5055
      - DEBUG=False
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: opera-panel-network
